apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: caddy
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: caddy
        tier: frontend
    spec:
      containers:
        - name: caddy
          image: caddy
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
